# Reinforcement Learning Chess
Hi there! If you're interested in learning about reinforcement learning, you are in the right place. As we all know the best way to learn about a topic is to build something and make a kernel about it. My plan is to make a series of notebooks where I work may way towards a full-fledged chess AI named RLC (Reinforcement Learning Chess). 

Tackling chess is a big challenge, mainly because of its huge state-space. Therefore I start with simpler forms of chess and solve these problems with elementary RL-techniques. Gradually I will expand this untill we end up in a chess AI that can play actual games of chess somewhat intelligibly. The forms of chess I want to cover in my notebooks are:  

#### 1. Move Chess 
- Goal: Learn to find the shortest path between 2 squares on a chess board  
- Motivation: Move Chess has a small statespace, which allows us to tackle this with simple RL algorithms.
- Concepts: Dynamic Programming, Policy Evaluation, Policy Improvement, Policy Iteration, Value Iteration, Synchronous & Asynchronous back-ups, Monte Carlo (MC) Prediction, MC Control, Temporal Difference (TD) Learning, TD control, TD-lambda, SARSA(-max)

#### 2. Capture Chess
- Goal: Capture as many pieces from the opponent within n fullmoves
- Motivation: Piece captures happen more frequently than win-lose-draw events. This give the algorithm more information to learn from.
- Concepts: Q-learning, value function approximation, experience replay, fixed-q-targets, policy gradients, REINFORCE, actor-critic


#### 3. Real Chess (a.k.a. chess)
- Goal: Play chess competitively against a human beginner
- Motivation: A RL chess AI
- Concepts: Monte Carlo Tree Search

#### Other notebooks
[**Notebook 2: Model free learning**](https://www.kaggle.com/arjanso/reinforcement-learning-chess-2-model-free-methods)  
[**Notebook 3: Q-networks**](https://www.kaggle.com/arjanso/reinforcement-learning-chess-3-q-networks)  
[**Notebook 4: Policy Gradients**](https://www.kaggle.com/arjanso/reinforcement-learning-chess-4-policy-gradients)  
[**Notebook 5: Monte Carlo Tree Search**](https://www.kaggle.com/arjanso/reinforcement-learning-chess-5-tree-search)


In my notebooks, I will describe and reference the Reinforcement Learning theory but I will not fully explain it. For that there are resources available that do a match better job at explaining RL than I could. For that my advice would be to check out David Silver's (Deepmind) lectures that are available on Youtube and the book Introduction to Reinforcement Learning by Sutton and Barto referenced below.

# Notebook I: Solving Move Chess

In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import os
import inspect

In [2]:
!pip install python-chess  # Python-Chess is the Python Chess Package that handles the chess environment
!pip install --upgrade git+https://github.com/arjangroen/RLC.git  # RLC is the Reinforcement Learning package

     |████████████████████████████████| 133kB 2.9MB/s 
  Cloning https://github.com/arjangroen/RLC.git to /tmp/pip-req-build-zieqpc5r
  Running command git clone -q https://github.com/arjangroen/RLC.git /tmp/pip-req-build-zieqpc5r
  Stored in directory: /tmp/pip-ephem-wheel-cache-tobocsdb/wheels/04/68/a5/cb835cd3d76a49de696a942739c71a56bfe66d0d8ea7b4b446
Successfully built RLC


In [3]:
%load_ext autoreload
%autoreload 2


In [4]:
from RLC.move_chess.environment import Board
from RLC.move_chess.agent import Piece
from RLC.move_chess.learn import Reinforce

### The environment

- The state space is a 8 by 8 grid
- The starting state S is the top-left square (0,0)
- The terminal state F is square (5,7). 
- Every move from state to state gives a reward of minus 1
- Naturally the best policy for this evironment is to move from S to F in the lowest amount of moves possible.

In [5]:
env = Board()
env.render()
env.visual_board

[['[S]', '[ ]', '[ ]', '[ ]', '[ ]', '[ ]', '[ ]', '[ ]'],
 ['[ ]', '[ ]', '[ ]', '[ ]', '[ ]', '[ ]', '[ ]', '[ ]'],
 ['[ ]', '[ ]', '[ ]', '[ ]', '[ ]', '[ ]', '[ ]', '[ ]'],
 ['[ ]', '[ ]', '[ ]', '[ ]', '[ ]', '[ ]', '[ ]', '[ ]'],
 ['[ ]', '[ ]', '[ ]', '[ ]', '[ ]', '[ ]', '[ ]', '[ ]'],
 ['[ ]', '[ ]', '[ ]', '[ ]', '[ ]', '[ ]', '[ ]', '[ ]'],
 ['[ ]', '[ ]', '[ ]', '[ ]', '[ ]', '[ ]', '[ ]', '[ ]'],
 ['[ ]', '[ ]', '[ ]', '[ ]', '[ ]', '[F]', '[ ]', '[ ]']]

### The agent
- The agent is a chess Piece (king, queen, rook, knight or bishop)
- The agent has a behavior policy determining what the agent does in what state

In [6]:
p = Piece(piece='king')

### Reinforce
- The reinforce object contains the algorithms for solving move chess
- The agent and the environment are attributes of the Reinforce object

In [7]:
r = Reinforce(p,env)

# 1.1 State Evaluation

**Theory**

If we want our agent to optimize its rewards, we want its policy to guide behavior towards the states with the highest value. This value can be estimated using bootstrapping:
* A state (s) is as valuable (V) as the successor state (s') plus the reward (R) for going from s to s'. 
* Since there can be mulitple actions (a) and multiple successor states they are summed and weighted by their probability (pi). 
* In a non-deterministic environment, a given action could result in multiple successor states. We don't have to take this into account for this problem because move chess is a deterministic game.
* Successor state values are discounted with discount factor (gamma) that varies between 0 and 1.  
* This gives us the following formula:  
![](http://incompleteideas.net/book/ebook/numeqnarraytmp7-2-2.png)  

Note that:
* The successor state value is also en estimate. 
* Evaluating a state is bootstrapping because you are making an estimate based on another estimate
* In the code you'll see a synchronous parameter that will be explained later in the policy evaluation section



**Python Implementation**

In [8]:
print(inspect.getsource(r.evaluate_state))

    def evaluate_state(self, state, gamma=0.9, synchronous=True):
        """
        Calculates the value of a state based on the successor states and the immediate rewards.
        Args:
            state: tuple of 2 integers 0-7 representing the state
            gamma: float, discount factor
            synchronous: Boolean

        Returns: The expected value of the state under the current policy.

        """
        greedy_action_value = np.max(self.agent.policy[state[0], state[1], :])
        greedy_indices = [i for i, a in enumerate(self.agent.policy[state[0], state[1], :]) if
                          a == greedy_action_value]  # List of all greedy actions
        prob = 1 / len(greedy_indices)  # probability of an action occuring
        state_value = 0
        for i in greedy_indices:
            self.env.state = state  # reset state to the one being evaluated
            reward, episode_end = self.env.step(self.agent.action_space[i])
            if synchronous:
           

**Demonstration**
* The initial value function assigns value 0 to each state
* The initial policy gives an equal probability to each action
* We evaluate state (0,0)

In [9]:
r.agent.value_function.astype(int)

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [10]:
state = (0,0)
r.agent.value_function[0,0] = r.evaluate_state(state,gamma=1)

In [11]:
r.agent.value_function.astype(int)

array([[-1,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])

# 1.2 Policy Evaluation
* Policy evaluation is the act of doe state evaluation for each state in the statespace
* As you can see in my implementatin I simply iterate over all state and update the value function
* This is the algorithm provided by Sutton and Barto:  
![](http://incompleteideas.net/book/ebook/pseudotmp0.png)


In [12]:
print(inspect.getsource(r.evaluate_policy))

    def evaluate_policy(self, gamma=0.9, synchronous=True):
        self.agent.value_function_prev = self.agent.value_function.copy()  # For synchronous updates
        for row in range(self.agent.value_function.shape[0]):
            for col in range(self.agent.value_function.shape[1]):
                self.agent.value_function[row, col] = self.evaluate_state((row, col), gamma=gamma,
                                                                          synchronous=synchronous)



In [13]:
r.evaluate_policy(gamma=1)

We end up with the following value of -1 for all states except the terminal state. 

In [14]:
r.agent.value_function.astype(int)

array([[-1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1,  0, -1, -1]])

We can iterate this until the value function is stable:

**Demonstration**

In [15]:
eps=0.1
k_max = 1000
value_delta_max = 0
gamma = 1
synchronous=True
value_delta_max = 0
for k in range(k_max):
    r.evaluate_policy(gamma=gamma,synchronous=synchronous)
    value_delta = np.max(np.abs(r.agent.value_function_prev - r.agent.value_function))
    value_delta_max = value_delta
    if value_delta_max < eps:
        print('converged at iter',k)
        break

converged at iter 428


This value function below shows the expected discounted future reward from state (0,0) = -185

In [16]:
r.agent.value_function.astype(int)

array([[-185, -183, -181, -179, -177, -175, -174, -175],
       [-182, -181, -179, -177, -174, -172, -171, -171],
       [-179, -177, -175, -172, -168, -166, -165, -164],
       [-174, -172, -169, -164, -160, -156, -154, -154],
       [-169, -167, -161, -154, -147, -142, -139, -139],
       [-164, -161, -154, -142, -131, -122, -119, -120],
       [-161, -157, -147, -131, -106,  -93,  -92, -102],
       [-160, -156, -145, -126,  -93,    0,  -77,  -93]])

# Policy Improvement

Now that we know what the values of the states are, we want to improve our Policy so that we the behavior is guided towards the state with the highest value. Policy Improvement is simply the act of making the policy greedy with respect to the value function.
* In my implementation, we do this by setting the value of the action that leads to the most valuable state to 1 (while the rest remains 0)

In [17]:
print(inspect.getsource(r.improve_policy))

    def improve_policy(self):
        """
        Finds the greedy policy w.r.t. the current value function
        """

        self.agent.policy_prev = self.agent.policy.copy()
        for row in range(self.agent.action_function.shape[0]):
            for col in range(self.agent.action_function.shape[1]):
                for action in range(self.agent.action_function.shape[2]):
                    self.env.state = (row, col)  # reset state to the one being evaluated
                    reward, episode_end = self.env.step(self.agent.action_space[action])
                    successor_state_value = 0 if episode_end else self.agent.value_function[self.env.state]
                    self.agent.policy[row, col, action] = reward + successor_state_value

                max_policy_value = np.max(self.agent.policy[row, col, :])
                max_indices = [i for i, a in enumerate(self.agent.policy[row, col, :]) if a == max_policy_value]
                for idx in max_indices:
             

In [18]:
r.improve_policy()
r.visualize_policy()

[['↘', '↘', '↘', '↘', '↘', '↘', '↓', '↙'],
 ['↘', '↘', '↘', '↘', '↘', '↘', '↘', '↓'],
 ['↘', '↘', '↘', '↘', '↘', '↘', '↘', '↓'],
 ['↘', '↘', '↘', '↘', '↘', '↘', '↘', '↓'],
 ['↘', '↘', '↘', '↘', '↘', '↘', '↓', '↙'],
 ['↘', '↘', '↘', '↘', '↘', '↘', '↓', '↙'],
 ['↘', '↘', '↘', '↘', '↘', '↓', '↙', '↙'],
 ['→', '→', '→', '→', '→', 'F', '←', '←']]


* Please note that my visual can print only 1 arrow per square, but there may be multiple optimal actions.

# 1.3 Policy Iteration  
**Theory**  
We can now find the optimal policy by doing policy evaluation and policy improvement untill the policy is stable:
![](http://www.incompleteideas.net/book/first/ebook/pseudotmp1.png)

**Python implementation**

In [19]:
print(inspect.getsource(r.policy_iteration))

    def policy_iteration(self, eps=0.1, gamma=0.9, iteration=1, k=32, synchronous=True):
        """
        Finds the optimal policy
        Args:
            eps: float, exploration rate
            gamma: float, discount factor
            iteration: the iteration number
            k: (int) maximum amount of policy evaluation iterations
            synchronous: (Boolean) whether to use synchronous are asynchronous back-ups 

        Returns:

        """
        policy_stable = True
        print("\n\n______iteration:", iteration, "______")
        print("\n policy:")
        self.visualize_policy()

        print("")
        value_delta_max = 0
        for _ in range(k):
            self.evaluate_policy(gamma=gamma, synchronous=synchronous)
            value_delta = np.max(np.abs(self.agent.value_function_prev - self.agent.value_function))
            value_delta_max = value_delta
            if value_delta_max < eps:
                break
        print("Value function for this po

**Demonstration**

In [20]:
r.policy_iteration()



______iteration: 1 ______

 policy:
[['↘', '↘', '↘', '↘', '↘', '↘', '↓', '↙'],
 ['↘', '↘', '↘', '↘', '↘', '↘', '↘', '↓'],
 ['↘', '↘', '↘', '↘', '↘', '↘', '↘', '↓'],
 ['↘', '↘', '↘', '↘', '↘', '↘', '↘', '↓'],
 ['↘', '↘', '↘', '↘', '↘', '↘', '↓', '↙'],
 ['↘', '↘', '↘', '↘', '↘', '↘', '↓', '↙'],
 ['↘', '↘', '↘', '↘', '↘', '↓', '↙', '↙'],
 ['→', '→', '→', '→', '→', 'F', '←', '←']]

Value function for this policy:
[[-5 -5 -5 -5 -5 -5 -5 -5]
 [-5 -5 -5 -5 -5 -5 -5 -5]
 [-4 -4 -4 -4 -4 -4 -4 -4]
 [-4 -3 -3 -3 -3 -3 -3 -3]
 [-4 -3 -3 -3 -3 -3 -3 -3]
 [-4 -3 -3 -2 -2 -2 -2 -2]
 [-4 -3 -3 -2 -1 -1 -1 -2]
 [-4 -3 -3 -2 -1  0 -1 -2]]

 Improving policy:
policy diff: False


______iteration: 2 ______

 policy:
[['↘', '↘', '↘', '↘', '↘', '↘', '↘', '↓'],
 ['↘', '↘', '↘', '↘', '↘', '↘', '↘', '↓'],
 ['↘', '↘', '↘', '↘', '↘', '↘', '↘', '↓'],
 ['→', '↘', '↘', '↘', '↘', '↘', '↘', '↓'],
 ['↗', '→', '↘', '↘', '↘', '↘', '↘', '↓'],
 ['↗', '↗', '→', '↘', '↘', '↘', '↓', '↙'],
 ['↗', '↗', '↗', '→', '↘', '↓', '

# 1.4 Asynchronous Policy Iteration


**Theory**  
With policy evaluation, we bootstrap: we make an estimate based on another estimate. So which estimate do we take? We have to options:
1. We bootstrap from the previous policy evaluation. This means each state value estimate update is based on the same iteration of policy evaluation. This is called synchronous policy iteration
2. We bootstrap from the freshest estimate. This means a estimate update can be based on the previous or the current value funtion, or a combination of the two. This is called asynchrronous policy iteration

The **Implementation** is the same as policy iteration, only we pass the argument sychronous=False

**Demonstration**

In [21]:
agent = Piece(piece='king')
r = Reinforce(agent,env)

In [22]:
r.policy_iteration(gamma=1,synchronous=False)



______iteration: 1 ______

 policy:
[['↑', '↑', '↑', '↑', '↑', '↑', '↑', '↑'],
 ['↑', '↑', '↑', '↑', '↑', '↑', '↑', '↑'],
 ['↑', '↑', '↑', '↑', '↑', '↑', '↑', '↑'],
 ['↑', '↑', '↑', '↑', '↑', '↑', '↑', '↑'],
 ['↑', '↑', '↑', '↑', '↑', '↑', '↑', '↑'],
 ['↑', '↑', '↑', '↑', '↑', '↑', '↑', '↑'],
 ['↑', '↑', '↑', '↑', '↑', '↑', '↑', '↑'],
 ['↑', '↑', '↑', '↑', '↑', 'F', '↑', '↑']]

Value function for this policy:
[[-47 -48 -48 -49 -48 -48 -48 -48]
 [-48 -49 -49 -49 -49 -49 -49 -49]
 [-49 -49 -49 -49 -49 -49 -48 -48]
 [-49 -49 -49 -49 -48 -47 -47 -47]
 [-49 -49 -48 -47 -46 -45 -44 -44]
 [-48 -48 -47 -44 -42 -40 -39 -39]
 [-48 -48 -46 -42 -34 -31 -31 -35]
 [-48 -48 -45 -41 -31   0 -27 -33]]

 Improving policy:
policy diff: False


______iteration: 2 ______

 policy:
[['↑', '←', '←', '←', '→', '→', '→', '↑'],
 ['↑', '↖', '↖', '↖', '↗', '↗', '↗', '↑'],
 ['↑', '↖', '↘', '↘', '↘', '↘', '↘', '↓'],
 ['↓', '↘', '↘', '↘', '↘', '↘', '↘', '↓'],
 ['↘', '↘', '↘', '↘', '↘', '↘', '↓', '↙'],
 ['↘', '↘', 

In [23]:
r.agent.value_function.astype(int)

array([[-5, -5, -5, -5, -5, -5, -5, -5],
       [-4, -4, -4, -4, -4, -4, -4, -4],
       [-4, -4, -4, -4, -4, -4, -4, -4],
       [-4, -3, -3, -3, -3, -3, -3, -3],
       [-4, -3, -2, -2, -2, -2, -2, -2],
       [-4, -3, -2, -1, -1, -1, -1, -1],
       [-4, -3, -2, -1, -1, -1, -1, -1],
       [-4, -3, -2, -1, -1,  0, -1, -1]])

# 1.5 Value Iteration

** Theory **  
Value iteration is nothing more than a simple parameter modification to policy iteration. Remember that policy iteration consists of policy evaluation and policy improvement. The policy evaluation step does not necessarily have to be repeated until convergence before we improve our policy. Recall that the policy iteration above took over 400 iterations to converge. If we use ony 1 iteration instead we call it value iteration.

**Demonstration**

In [24]:
agent = Piece(piece='rook')  # Let's pick a rook for a change.
r = Reinforce(agent,env)
r.policy_iteration(k=1,gamma=1)  # The only difference here is that we set k_max to 1.



______iteration: 1 ______

 policy:
[['↑', '↑', '↑', '↑', '↑', '↑', '↑', '↑'],
 ['↑', '↑', '↑', '↑', '↑', '↑', '↑', '↑'],
 ['↑', '↑', '↑', '↑', '↑', '↑', '↑', '↑'],
 ['↑', '↑', '↑', '↑', '↑', '↑', '↑', '↑'],
 ['↑', '↑', '↑', '↑', '↑', '↑', '↑', '↑'],
 ['↑', '↑', '↑', '↑', '↑', '↑', '↑', '↑'],
 ['↑', '↑', '↑', '↑', '↑', '↑', '↑', '↑'],
 ['↑', '↑', '↑', '↑', '↑', 'F', '↑', '↑']]

Value function for this policy:
[[-1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1  0 -1 -1]]

 Improving policy:
policy diff: False


______iteration: 2 ______

 policy:
[['↑', '↑', '↑', '↑', '↑', '↓', '↑', '↑'],
 ['↑', '↑', '↑', '↑', '↑', '↓', '↑', '↑'],
 ['↑', '↑', '↑', '↑', '↑', '↓', '↑', '↑'],
 ['↑', '↑', '↑', '↑', '↑', '↓', '↑', '↑'],
 ['↑', '↑', '↑', '↑', '↑', '↓', '↑', '↑'],
 ['↑', '↑', '↑', '↑', '↑', '↓', '↑', '↑'],
 ['↑', '↑', '↑', '↑', '↑', '↓', '

# That's all!
In the next notebook I'll cover model-free methods such as Monte Carlo and Temporal Difference based methods. These methods help us when we don't know the transition probalities of a Markov Decision Process. 

I expect to have my second RLC notebook up and running around mid-june!
Hope you enjoyed!

# References

1. Reinforcement Learning: An Introduction  
   Richard S. Sutton and Andrew G. Barto  
   1st Edition  
   MIT Press, march 1998
2. RL Course by David Silver: Lecture playlist  
   https://www.youtube.com/watch?v=2pWv7GOvuf0&list=PLqYmG7hTraZDM-OYHWgPebj2MfCFzFObQ